name: dietapp
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Theming
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Navigation
  go_router: ^14.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage & Persistence
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.20.2  # Formattazione date/numeri
  uuid: ^4.2.1   # Generazione ID univoci

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/macros/
    - assets/icons/meals/
    - assets/icons/tracking/
